apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: employees
  namespace: webapp-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app-container
        image: 945233852280.dkr.ecr.us-east-1.amazonaws.com/apprepo:v0.1
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-namespace.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "vbbarot"
          