apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  namespace: webapp-namespace
  labels:
   app: employees 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app-container
        image: 945233852280.dkr.ecr.us-east-1.amazonaws.com/apprepo:v0.0
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "mysql-service.mysql-namespace.svc.cluster.local"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: vbbarot
        ports:
        - containerPort: 8080