apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
  labels:
   app: mysql 
spec:
  containers:
  - name: sql-container
    image: 945233852280.dkr.ecr.us-east-1.amazonaws.com/mysqlrepo:v0.0  # or the image for your preferred SQL database
    ports:
    - containerPort: 3306   # Replace with the port your SQL database listens on
    env:
    - name: MYSQL_ROOT_PASSWORD   # Replace with your desired environment variables
      value: "vbbarot"
